/* =========================================================
   DIGITAL STUDIO — LANGUAGE (English / বাংলা / हिन्दी)
   এখানে নতুন কোনো লেখা যোগ করতে চাইলে তিনটে ভাষাতেই একটা করে
   লাইন যোগ করবেন, key একই রাখবেন।
   ========================================================= */

const TRANSLATIONS = {
  en: {
    appName: "Digital Studio",
    tagline: "Your complete guide for exams, current affairs & more",
    loginTitle: "Login",
    gmailPhone: "Gmail / Phone Number",
    password: "Password",
    loginBtn: "Login",
    newHere: "New to website?",
    clickRegister: "Click here to register",
    adminLogin: "Admin Login",
    registerTitle: "Create your account",
    name: "Name",
    fatherName: "Father's Name",
    phone: "Phone Number",
    email: "Email",
    rePassword: "Re-enter Password",
    village: "Village",
    postOffice: "Post Office",
    pinCode: "Pin Code",
    district: "District",
    addressLine: "Address Line",
    registerBtn: "Register",
    backToLogin: "Back to login",
    welcome: "Welcome",
    statUsers: "Active Users",
    statBenefited: "Students Benefited",
    statRating: "Our Rating",
    outOf10: "/ 10",
    menu: "Menu",
    dailyCurrentAffairs: "Daily Current Affairs",
    mockTests: "Mock Tests",
    wbcsNotes: "WBCS Notes",
    wbpscNotes: "WBPSC Notes",
    gramPanchayat: "WB Grampanchayat Notes",
    sscRailway: "SSC & Railway Notes",
    deledNotes: "D.El.Ed Part I/II Notes",
    tetNotes: "TET Notes",
    ctetNotes: "CTET Notes",
    jobNotif: "Job Notifications",
    scholarshipNotif: "Scholarship Notifications",
    notAvailable: "Not available yet",
    comingSoon: "This service isn't ready yet — coming soon.",
    logout: "Logout",
    language: "Website Language",
    errPhoneDigits: "Phone number must be exactly 10 digits",
    errPhoneTaken: "This number is already registered",
    errEmailFormat: "Please enter a valid email address",
    errEmailTaken: "This email is already registered",
    errPasswordMatch: "Passwords do not match",
    errRequired: "Please fill all required fields",
    errLoginFailed: "Incorrect Gmail/Phone or password",
    errAccountBlocked: "Your account has been blocked. Contact admin.",
    errBackendNotSet: "Backend not connected yet. Please set APPS_SCRIPT_URL in config.js",
    registerSuccess: "Registration successful! Please login.",
    back: "Back",
    adminPanel: "Admin Panel",
    userProfiles: "User Profiles",
    accessBtn: "Access",
    blockBtn: "Block",
    unblockBtn: "Unblock",
    deleteBtn: "Delete",
    confirmTitle: "Warning",
    confirmMsg: "Are you sure?",
    yes: "Yes",
    no: "No",
    addNew: "Add New",
    fileName: "File Name",
    addText: "Add Text",
    save: "Save",
    quizName: "Quiz Name",
    duration: "Duration (minutes)",
    addQuestion: "Add Question",
    question: "Question",
    option: "Option",
    correctMarks: "Correct Marks",
    negativeMarks: "Negative Marks",
    explanation: "Explanation",
    imageOptional: "Image URL (optional)",
    startTest: "Start Test",
    submitTest: "Submit Test",
    timeLeft: "Time Left",
    yourScore: "Your Score",
    correct: "Correct",
    wrong: "Wrong",
    unanswered: "Unanswered",
    viewResults: "View Results",
    student: "Student",
    score: "Score",
    timeTaken: "Time Taken",
    viewAnswers: "View Answers",
    close: "Close",
    availableFrom: "This service will be available from 01 October 2026",
    loading: "Loading...",
    noData: "Nothing here yet."
  },
  bn: {
    appName: "ডিজিটাল স্টুডিও",
    tagline: "পরীক্ষা, কারেন্ট অ্যাফেয়ার্স ও আরও অনেক কিছুর জন্য আপনার সম্পূর্ণ গাইড",
    loginTitle: "লগইন",
    gmailPhone: "জিমেইল / ফোন নম্বর",
    password: "পাসওয়ার্ড",
    loginBtn: "লগইন",
    newHere: "ওয়েবসাইটে নতুন?",
    clickRegister: "রেজিস্টার করতে এখানে ক্লিক করুন",
    adminLogin: "অ্যাডমিন লগইন",
    registerTitle: "আপনার অ্যাকাউন্ট তৈরি করুন",
    name: "নাম",
    fatherName: "বাবার নাম",
    phone: "ফোন নম্বর",
    email: "ইমেইল",
    rePassword: "পাসওয়ার্ড আবার লিখুন",
    village: "গ্রাম",
    postOffice: "পোস্ট অফিস",
    pinCode: "পিন কোড",
    district: "জেলা",
    addressLine: "ঠিকানা",
    registerBtn: "রেজিস্টার",
    backToLogin: "লগইনে ফিরে যান",
    welcome: "স্বাগতম",
    statUsers: "সক্রিয় ব্যবহারকারী",
    statBenefited: "উপকৃত শিক্ষার্থী",
    statRating: "আমাদের রেটিং",
    outOf10: "/ ১০",
    menu: "মেনু",
    dailyCurrentAffairs: "দৈনিক কারেন্ট অ্যাফেয়ার্স",
    mockTests: "মক টেস্ট",
    wbcsNotes: "WBCS নোটস",
    wbpscNotes: "WBPSC নোটস",
    gramPanchayat: "WB গ্রামপঞ্চায়েত নোটস",
    sscRailway: "SSC ও রেলওয়ে নোটস",
    deledNotes: "D.El.Ed পার্ট ১/২ নোটস",
    tetNotes: "TET নোটস",
    ctetNotes: "CTET নোটস",
    jobNotif: "চাকরির খবর",
    scholarshipNotif: "স্কলারশিপের খবর",
    notAvailable: "এখনও উপলব্ধ নয়",
    comingSoon: "এই সার্ভিসটি এখনও প্রস্তুত নয় — শীঘ্রই আসছে।",
    logout: "লগআউট",
    language: "ওয়েবসাইট ভাষা",
    errPhoneDigits: "ফোন নম্বর অবশ্যই ১০ ডিজিটের হতে হবে",
    errPhoneTaken: "এই নম্বরটি ইতিমধ্যে রেজিস্টার্ড",
    errEmailFormat: "সঠিক ইমেইল ফরম্যাট লিখুন",
    errEmailTaken: "এই ইমেইলটি ইতিমধ্যে রেজিস্টার্ড",
    errPasswordMatch: "পাসওয়ার্ড মিলছে না",
    errRequired: "সব প্রয়োজনীয় ঘর পূরণ করুন",
    errLoginFailed: "ভুল জিমেইল/ফোন অথবা পাসওয়ার্ড",
    errAccountBlocked: "আপনার অ্যাকাউন্ট ব্লক করা হয়েছে। অ্যাডমিনের সাথে যোগাযোগ করুন।",
    errBackendNotSet: "ব্যাকএন্ড এখনও যুক্ত হয়নি। config.js এ APPS_SCRIPT_URL বসান।",
    registerSuccess: "রেজিস্ট্রেশন সফল হয়েছে! এবার লগইন করুন।",
    back: "ফিরে যান",
    adminPanel: "অ্যাডমিন প্যানেল",
    userProfiles: "ইউজার প্রোফাইল",
    accessBtn: "অ্যাক্সেস",
    blockBtn: "ব্লক",
    unblockBtn: "আনব্লক",
    deleteBtn: "ডিলিট",
    confirmTitle: "সতর্কবার্তা",
    confirmMsg: "আপনি কি নিশ্চিত?",
    yes: "হ্যাঁ",
    no: "না",
    addNew: "নতুন যোগ করুন",
    fileName: "ফাইলের নাম",
    addText: "লেখা যোগ করুন",
    save: "সেভ",
    quizName: "কুইজের নাম",
    duration: "সময় (মিনিটে)",
    addQuestion: "প্রশ্ন যোগ করুন",
    question: "প্রশ্ন",
    option: "অপশন",
    correctMarks: "সঠিক নম্বর",
    negativeMarks: "নেগেটিভ নম্বর",
    explanation: "ব্যাখ্যা",
    imageOptional: "ছবির লিংক (ঐচ্ছিক)",
    startTest: "টেস্ট শুরু করুন",
    submitTest: "টেস্ট জমা দিন",
    timeLeft: "বাকি সময়",
    yourScore: "আপনার স্কোর",
    correct: "সঠিক",
    wrong: "ভুল",
    unanswered: "উত্তর দেওয়া হয়নি",
    viewResults: "ফলাফল দেখুন",
    student: "শিক্ষার্থী",
    score: "স্কোর",
    timeTaken: "সময় নিয়েছে",
    viewAnswers: "উত্তর দেখুন",
    close: "বন্ধ করুন",
    availableFrom: "এই সার্ভিসটি ০১ অক্টোবর ২০২৬ থেকে চালু হবে",
    loading: "লোড হচ্ছে...",
    noData: "এখানে এখনও কিছু নেই।"
  },
  hi: {
    appName: "डिजिटल स्टूडियो",
    tagline: "परीक्षा, करंट अफेयर्स और अन्य सेवाओं के लिए आपका संपूर्ण गाइड",
    loginTitle: "लॉगिन",
    gmailPhone: "जीमेल / फोन नंबर",
    password: "पासवर्ड",
    loginBtn: "लॉगिन",
    newHere: "वेबसाइट पर नए हैं?",
    clickRegister: "रजिस्टर करने के लिए यहाँ क्लिक करें",
    adminLogin: "एडमिन लॉगिन",
    registerTitle: "अपना अकाउंट बनाएं",
    name: "नाम",
    fatherName: "पिता का नाम",
    phone: "फोन नंबर",
    email: "ईमेल",
    rePassword: "पासवर्ड दोबारा लिखें",
    village: "गाँव",
    postOffice: "पोस्ट ऑफिस",
    pinCode: "पिन कोड",
    district: "जिला",
    addressLine: "पता",
    registerBtn: "रजिस्टर",
    backToLogin: "लॉगिन पर वापस जाएं",
    welcome: "स्वागत है",
    statUsers: "सक्रिय उपयोगकर्ता",
    statBenefited: "लाभान्वित छात्र",
    statRating: "हमारी रेटिंग",
    outOf10: "/ १०",
    menu: "मेनू",
    dailyCurrentAffairs: "दैनिक करंट अफेयर्स",
    mockTests: "मॉक टेस्ट",
    wbcsNotes: "WBCS नोट्स",
    wbpscNotes: "WBPSC नोट्स",
    gramPanchayat: "WB ग्रामपंचायत नोट्स",
    sscRailway: "SSC व रेलवे नोट्स",
    deledNotes: "D.El.Ed भाग 1/2 नोट्स",
    tetNotes: "TET नोट्स",
    ctetNotes: "CTET नोट्स",
    jobNotif: "नौकरी सूचनाएं",
    scholarshipNotif: "छात्रवृत्ति सूचनाएं",
    notAvailable: "अभी उपलब्ध नहीं है",
    comingSoon: "यह सेवा अभी तैयार नहीं है — जल्द आ रही है।",
    logout: "लॉगआउट",
    language: "वेबसाइट भाषा",
    errPhoneDigits: "फोन नंबर 10 अंकों का होना चाहिए",
    errPhoneTaken: "यह नंबर पहले से रजिस्टर्ड है",
    errEmailFormat: "कृपया सही ईमेल फॉर्मेट लिखें",
    errEmailTaken: "यह ईमेल पहले से रजिस्टर्ड है",
    errPasswordMatch: "पासवर्ड मेल नहीं खाता",
    errRequired: "कृपया सभी आवश्यक जानकारी भरें",
    errLoginFailed: "गलत जीमेल/फोन या पासवर्ड",
    errAccountBlocked: "आपका खाता ब्लॉक कर दिया गया है। एडमिन से संपर्क करें।",
    errBackendNotSet: "बैकएंड अभी जुड़ा नहीं है। config.js में APPS_SCRIPT_URL डालें।",
    registerSuccess: "रजिस्ट्रेशन सफल! अब लॉगिन करें।",
    back: "वापस जाएं",
    adminPanel: "एडमिन पैनल",
    userProfiles: "यूजर प्रोफाइल",
    accessBtn: "एक्सेस",
    blockBtn: "ब्लॉक",
    unblockBtn: "अनब्लॉक",
    deleteBtn: "डिलीट",
    confirmTitle: "चेतावनी",
    confirmMsg: "क्या आप वाकई करना चाहते हैं?",
    yes: "हाँ",
    no: "नहीं",
    addNew: "नया जोड़ें",
    fileName: "फ़ाइल नाम",
    addText: "टेक्स्ट जोड़ें",
    save: "सेव करें",
    quizName: "क्विज़ का नाम",
    duration: "अवधि (मिनट)",
    addQuestion: "प्रश्न जोड़ें",
    question: "प्रश्न",
    option: "विकल्प",
    correctMarks: "सही अंक",
    negativeMarks: "नकारात्मक अंक",
    explanation: "व्याख्या",
    imageOptional: "इमेज लिंक (वैकल्पिक)",
    startTest: "टेस्ट शुरू करें",
    submitTest: "टेस्ट जमा करें",
    timeLeft: "बचा समय",
    yourScore: "आपका स्कोर",
    correct: "सही",
    wrong: "गलत",
    unanswered: "अनुत्तरित",
    viewResults: "परिणाम देखें",
    student: "छात्र",
    score: "स्कोर",
    timeTaken: "लिया गया समय",
    viewAnswers: "उत्तर देखें",
    close: "बंद करें",
    availableFrom: "यह सेवा 01 अक्टूबर 2026 से उपलब्ध होगी",
    loading: "लोड हो रहा है...",
    noData: "यहाँ अभी कुछ भी नहीं है।"
  }
};

let currentLang = localStorage.getItem("ds_lang") || "en";

function t(key) {
  return (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key]) || TRANSLATIONS.en[key] || key;
}

function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem("ds_lang", lang);
  applyTranslations();
}

function applyTranslations() {
  document.querySelectorAll("[data-i18n]").forEach(el => {
    el.textContent = t(el.getAttribute("data-i18n"));
  });
  document.querySelectorAll("[data-i18n-ph]").forEach(el => {
    el.setAttribute("placeholder", t(el.getAttribute("data-i18n-ph")));
  });
  document.documentElement.setAttribute("lang", currentLang);
}
